####################################################################
# Sytem Parameters
####################################################################

SYS_PARAMS:
    m: 35.0                 # COM mass,[kg] 
    g: 9.81                 # gravity, [m/s^2] 
    k: 7500.0               # spring stiffness, [N/m]
    b: 50.0                 # damping coeff, [Ns/m]
    l0: 0.65                # nominal rest length, [m]
    r_min: 0.4              # min leg length, [m]
    r_max: 0.8              # max leg length, [m]
    theta_min: -1.0         # min leg angle, [rad]
    theta_max: 1.0          # max leg angle, [rad]
    rdot_lim: 1.0           # max leg velocity [m/s]
    thetadot_lim: 3.14      # max angle velocity [rad/s]
    torque_ankle: True      # whether or not to enable the ankle torque
    torque_ankle_lim: 10.0  # ankle torque limit, [Nm]
    torque_ankle_kp: 125.0  # ankle torque proportional gain
    torque_ankle_kd: 10.0   # ankle torque derivative gain
    interp: 'L'             # control interpolation method

####################################################################
# Controller Parameters
####################################################################

CTRL_PARAMS:
    N: 100                          # number of time steps
    dt: 0.01                        # time step, [s]
    K: 1000                         # number of rollouts
    Nu: 25                          # number of control points
    Q_diags:  [0.0, 5.0, 2.0, 0.05, # diagonal elements of the cost matrix
               5.0, 5.0, 0.1, 1.0]   
    Qf_diags: [0.0, 5.0, 2.0, 0.05, # diagonal elements of the terminal cost matrix
               5.0, 5.0, 0.1, 1.0]  
    R_diags: [0.1, 0.1]             # diagonal elements of the control cost matrix
    N_elite: 100                    # number of elite samples
    CEM_iters: 20                   # number of CEM iterations

####################################################################
# Distribution Parameters
####################################################################

DIST_PARAMS:
    mu: [0., 0.8]              # initial means [l0dot_vel, thetadot_vel]
    sigma: [0.0000001, 0.01]           # initial standard deviations
    min_varaince: [0.05, 0.05]  # minimum variance of the state distribution
    diag_cov: False             # strictly enforce diagonal covariance matrix
    seed_enabled: False         # enable random seed
    seed: 0                     # random seed