####################################################################
# Sytem Parameters
####################################################################

SYS_PARAMS:
    m: 35.0                 # COM mass,[kg] 
    g: 9.81                 # gravity, [m/s^2] 
    k: 5000.0               # spring stiffness, [N/m]
    b: 50.0                 # damping coeff, [Ns/m]
    l0: 0.65                # nominal rest length, [m]
    r_min: 0.1              # min leg length, [m]
    r_max: 0.2              # max leg length, [m]
    theta_min: 0.0          # min leg angle, [rad]
    theta_max: 2.0          # max leg angle, [rad]
    rdot_lim: 0.1           # max leg velocity [m/s]
    thetadot_lim: 0.1       # max angle velocity [rad/s]
    torque_ankle: True      # whether or not to enable the ankle torque
    torque_ankle_kp: 100.0  # ankle torque proportional gain
    torque_ankle_kd: 10.0   # ankle torque derivative gain

####################################################################
# Controller Parameters
####################################################################

# CTRL_PARAMS:
